/**
 * KESCO DTPulse — Design tokens
 * Theme palette:
 *   Background #fffffe · Headline/Paragraph/Stroke #2b2c34
 *   Button/Highlight #6246ea · Button text/Main #fffffe
 *   Secondary #d1d1e9 · Tertiary #e45858
 */

const colors = {
  light: {
    text:                '#2b2c34',
    tint:                '#6246ea',
    background:          '#fffffe',
    foreground:          '#2b2c34',
    card:                '#fffffe',
    cardForeground:      '#2b2c34',
    primary:             '#6246ea',
    primaryForeground:   '#fffffe',
    secondary:           '#d1d1e9',
    secondaryForeground: '#2b2c34',
    muted:               '#d1d1e9',
    mutedForeground:     '#6b6b7e',
    accent:              '#6246ea',
    accentForeground:    '#fffffe',
    destructive:         '#e45858',
    destructiveForeground: '#fffffe',
    destructiveBg:       '#fde8e8',
    warning:             '#D97706',
    warningForeground:   '#fffffe',
    warningBg:           '#FEF3C7',
    success:             '#059669',
    successForeground:   '#fffffe',
    successBg:           '#D1FAE5',
    border:              '#d1d1e9',
    input:               '#d1d1e9',
    tabBar:              '#fffffe',
    tabBarBorder:        '#d1d1e9',
    shadow:              'rgba(43, 44, 52, 0.12)',
    overlay:             'rgba(43, 44, 52, 0.5)',
    chartBar1:           '#6246ea',
    chartBar2:           '#e45858',
    chartBar3:           '#9c86f0',
    chartLine1:          '#e45858',
    chartLine2:          '#6246ea',
    chartLine3:          '#9c86f0',
  },
  dark: {
    text:                '#e8e8f0',
    tint:                '#9c86f0',
    background:          '#16161e',
    foreground:          '#e8e8f0',
    card:                '#1e1e2a',
    cardForeground:      '#e8e8f0',
    primary:             '#6246ea',
    primaryForeground:   '#fffffe',
    secondary:           '#2e2e3e',
    secondaryForeground: '#e8e8f0',
    muted:               '#2e2e3e',
    mutedForeground:     '#9090a8',
    accent:              '#6246ea',
    accentForeground:    '#fffffe',
    destructive:         '#e45858',
    destructiveForeground: '#fffffe',
    destructiveBg:       '#3a1a1a',
    warning:             '#F59E0B',
    warningForeground:   '#16161e',
    warningBg:           '#3a2a08',
    success:             '#10B981',
    successForeground:   '#fffffe',
    successBg:           '#063d2e',
    border:              '#3a3a50',
    input:               '#3a3a50',
    tabBar:              '#16161e',
    tabBarBorder:        '#2e2e3e',
    shadow:              'rgba(0, 0, 0, 0.4)',
    overlay:             'rgba(0, 0, 0, 0.7)',
    chartBar1:           '#6246ea',
    chartBar2:           '#e45858',
    chartBar3:           '#9c86f0',
    chartLine1:          '#e45858',
    chartLine2:          '#6246ea',
    chartLine3:          '#9c86f0',
  },
  radius: 12,
};

export default colors;
